const List<String> masterWordsList = [
  "assault",
  "continuation",
  "question",
  "hilarious",
  "hip",
  "restless",
  "hear",
  "admission",
  "wire",
  "education",
  "particle",
  "hospitality",
  "silence",
  "assignment",
  "spray",
  "freckle",
  "palm",
  "pattern",
  "buttocks",
  "pavement",
  "exempt",
  "video",
  "gun",
  "seller",
  "property",
  "mark",
  "coat",
  "analysis",
  "can",
  "strain",
  "motif",
  "leftovers",
  "bacon",
  "heir",
  "follow",
  "moment",
  "egg",
  "stroke",
  "facility",
  "frame",
  "gain",
  "ferry",
  "exchange",
  "branch",
  "ticket",
  "whole",
  "attack",
  "stride",
  "gravity",
  "aid",
  "mastermind",
  "disclose",
  "original",
  "death",
  "passage",
  "chest",
  "safari",
  "broccoli",
  "endure",
  "allocation",
  "landowner",
  "breakdown",
  "south",
  "sin",
  "mole",
  "director",
  "grass",
  "line",
  "major",
  "overview",
  "helicopter",
  "hike",
  "calculation",
  "ambiguity",
  "partnership",
  "harass",
  "insist",
  "waterfall",
  "squash",
  "sample",
  "leak",
  "food",
  "full",
  "mushroom",
  "wander",
  "stomach",
  "crude",
  "officer",
  "fuel",
  "soldier",
  "word",
  "reckless",
  "fuss",
  "linen",
  "flesh",
  "collar",
  "glory",
  "scrap",
  "integration",
  "designer",
  "sport",
  "miner",
  "aspect",
  "replacement",
  "demonstrator",
  "scatter",
  "tasty",
  "enlarge",
  "achieve",
  "talk",
  "cabin",
  "tourist",
  "say",
  "no",
  "strip",
  "gem",
  "judgment",
  "bear",
  "loan",
  "money",
  "favor",
  "panic",
  "warrant",
  "quote",
  "flat",
  "summary",
  "index",
  "address",
  "stimulation",
  "economy",
  "responsibility",
  "survey",
  "moon",
  "bus",
  "finished",
  "fit",
  "breeze",
  "wake",
  "minority",
  "recruit",
  "exotic",
  "deny",
  "jail",
  "moving",
  "heroin",
  "wound",
  "notion",
  "socialist",
  "mature",
  "mug",
];

const SEQUENCE_MEMORY_STORIES = [
  {
    'context': 'Emma\'s morning routine',
    'events': [
      'Emma woke up at 7:00 AM',
      'She took a shower and got dressed',
      'Emma made breakfast in the kitchen',
      'She ate breakfast while reading the news',
      'Emma packed her bag for work',
      'She left home at 8:15 AM',
      'Emma arrived at the office at 8:45 AM',
      'She started working on her first task',
    ],
  },
  {
    'context': 'A day at the beach',
    'events': [
      'The family arrived at the beach early',
      'They set up their umbrella and towels',
      'The children built a sandcastle',
      'Everyone went swimming in the ocean',
      'They had lunch on the beach',
      'The kids played beach volleyball',
      'The sun started to set',
      'The family packed up and went home',
    ],
  },
  {
    'context': 'Preparing for a dinner party',
    'events': [
      'Sarah decided to host a dinner party',
      'She made a shopping list',
      'Sarah went to the grocery store',
      'She prepared the appetizers',
      'The main course was put in the oven',
      'Guests started arriving at 7 PM',
      'Everyone sat down for dinner',
      'They enjoyed dessert and coffee',
    ],
  },
  {
    'context': 'A hiking adventure',
    'events': [
      'The group met at the trailhead',
      'They started hiking up the mountain',
      'They took a break at the midpoint',
      'The view from the top was amazing',
      'They had a picnic lunch',
      'They took photos at the summit',
      'The group started descending',
      'They arrived back at the trailhead',
    ],
  },
  // 50 additional stories start here
  {
    'context': 'Moving to a new apartment',
    'events': [
      'Alex packed the last few boxes',
      'The moving truck arrived at 9 AM',
      'They loaded furniture carefully',
      'Alex drove to the new apartment',
      'They unloaded everything inside',
      'Essential items were unpacked first',
      'Alex ordered pizza for dinner',
      'They fell asleep on their new couch',
    ],
  },
  {
    'context': 'A trip to the library',
    'events': [
      'Maria walked to the library',
      'She returned her overdue books',
      'Maria browsed the fiction section',
      'She found three promising novels',
      'She checked them out at the desk',
      'Maria stopped at a café nearby',
      'She read the first chapter over coffee',
      'She walked home feeling content',
    ],
  },
  {
    'context': 'Baking a birthday cake',
    'events': [
      'Lisa preheated the oven to 350°F',
      'She mixed flour and sugar in a bowl',
      'Eggs and butter were added next',
      'The batter was poured into a pan',
      'Lisa placed it in the oven',
      'She prepared chocolate frosting',
      'The cake cooled on a wire rack',
      'Lisa decorated it with sprinkles',
    ],
  },
  {
    'context': 'Rainy day at home',
    'events': [
      'Heavy rain woke Tom early',
      'He made coffee and lit a fire',
      'Tom found his favorite blanket',
      'He chose a classic movie to watch',
      'Popcorn was popped in the kitchen',
      'He watched the movie by the fire',
      'Tom took a nap during the storm',
      'He woke up to find the sun shining',
    ],
  },
  {
    'context': 'Visiting grandparents',
    'events': [
      'The family packed the car early',
      'They drove two hours to the countryside',
      'Grandma waited at the front door',
      'Grandpa showed his garden updates',
      'They shared lunch in the dining room',
      'Everyone looked through old photo albums',
      'The kids played with vintage toys',
      'They said goodbye after dinner',
    ],
  },
  {
    'context': 'Gardening day',
    'events': [
      'Jenny put on her gardening gloves',
      'She weeded the vegetable patch',
      'Tomato plants were staked properly',
      'Jenny watered all the beds',
      'She planted new lettuce seeds',
      'Mulch was spread around the flowers',
      'She harvested ripe cucumbers',
      'Jenny cleaned her tools before storing',
    ],
  },
  {
    'context': 'A trip to the museum',
    'events': [
      'David arrived at the museum at opening',
      'He visited the dinosaur exhibit first',
      'Modern art section was next on his list',
      'David attended a guided tour',
      'He stopped for lunch at the café',
      'Ancient artifacts caught his attention',
      'He bought a souvenir at the gift shop',
      'David left just before closing time',
    ],
  },
  {
    'context': 'Studying for an exam',
    'events': [
      'Rachel cleared her desk completely',
      'She organized her study materials',
      'Flashcards were created for key terms',
      'Rachel took a practice test',
      'She reviewed her wrong answers',
      'A study break was taken at 3 PM',
      'More notes were reviewed before dinner',
      'Rachel went to bed early to rest',
    ],
  },
  {
    'context': 'Going to the gym',
    'events': [
      'Chris packed his gym bag the night before',
      'He arrived at the gym by 6:30 AM',
      'Fifteen minutes were spent on the treadmill',
      'He lifted weights for thirty minutes',
      'Chris did core exercises next',
      'He stretched thoroughly afterward',
      'A protein shake was purchased at the bar',
      'He showered and headed to work',
    ],
  },
  {
    'context': 'Movie night with friends',
    'events': [
      'Amanda invited friends over',
      'She set up the projector in the living room',
      'Popcorn and snacks were prepared',
      'Friends arrived with more drinks',
      'They voted on which movie to watch',
      'The movie started at 8 PM sharp',
      'Everyone discussed it afterward',
      'They cleaned up together before leaving',
    ],
  },
  {
    'context': 'Shopping for new clothes',
    'events': [
      'Taylor took the train downtown',
      'First stop was the department store',
      'Three shirts were tried on',
      'A pair of jeans fit perfectly',
      'Taylor found shoes on sale',
      'Accessories were purchased at a boutique',
      'Everything was paid for at the register',
      'Taylor treated herself to ice cream after',
    ],
  },
  {
    'context': 'A day at the amusement park',
    'events': [
      'The gates opened at 10 AM',
      'They rushed to the roller coaster first',
      'A long line formed by noon',
      'They ate hot dogs for lunch',
      'Water rides were perfect for the heat',
      'They won a stuffed animal at a game',
      'Cotton candy was shared at sunset',
      'Fireworks ended the perfect day',
    ],
  },
  {
    'context': 'Camping trip',
    'events': [
      'They reached the campsite before dark',
      'Tents were pitched near the lake',
      'Firewood was gathered from the forest',
      'A campfire was started successfully',
      'Dinner was cooked over the flames',
      'Stories were shared under the stars',
      'They retired to their sleeping bags',
      'Birds woke them at dawn',
    ],
  },
  {
    'context': 'Cleaning the house',
    'events': [
      'Rebecca started with the kitchen',
      'Dishes were washed and put away',
      'She vacuumed every carpeted room',
      'Bathrooms were scrubbed thoroughly',
      'Dust was wiped from all surfaces',
      'Laundry was sorted and started',
      'She mopped the hardwood floors',
      'Air freshener was sprayed throughout',
    ],
  },
  {
    'context': 'Painting a room',
    'events': [
      'Furniture was moved to the center',
      'Drop cloths protected the floor',
      'Tape was applied to trim and edges',
      'Primer was rolled onto the walls',
      'The first coat of paint was applied',
      'A second coat was added after drying',
      'The tape was carefully removed',
      'Furniture was returned to place',
    ],
  },
  {
    'context': 'Car repair day',
    'events': [
      'Mark noticed a strange engine noise',
      'He drove to the auto shop',
      'The mechanic diagnosed the problem',
      'Mark approved the necessary repairs',
      'He waited in the lobby for two hours',
      'The car was ready by afternoon',
      'Mark paid the bill at the counter',
      'The engine ran smoothly driving home',
    ],
  },
  {
    'context': 'A walk in the park',
    'events': [
      'Sophie leashed her golden retriever',
      'They entered the park at the north gate',
      'The dog ran freely in the off-leash area',
      'Sophie chatted with other dog owners',
      'They walked the loop trail twice',
      'A water break was taken at the fountain',
      'They rested on a bench by the pond',
      'Sophie and her dog headed home tired',
    ],
  },
  {
    'context': 'Coffee shop work session',
    'events': [
      'James found a corner table with outlets',
      'He ordered a large latte and pastry',
      'His laptop was set up quickly',
      'James answered urgent emails first',
      'He worked on a presentation slide deck',
      'A refill was needed after an hour',
      'Background noise helped him focus',
      'James packed up after three hours',
    ],
  },
  {
    'context': 'Concert evening',
    'events': [
      'Sarah arrived at the venue early',
      'She found her seat in the orchestra',
      'The opening band played three songs',
      'There was a twenty-minute intermission',
      'The main act started with pyrotechnics',
      'Sarah sang along to every song',
      'An encore was performed after the set',
      'She bought a tour shirt at the merch stand',
    ],
  },
  {
    'context': 'Airport pickup',
    'events': [
      'Michael checked the flight status online',
      'He left home with time to spare',
      'Parking was found in the short-term lot',
      'He waited at the arrivals gate',
      'Grandparents emerged from customs',
      'They helped with the luggage trolley',
      'Everyone stopped for coffee on the way out',
      'Michael drove them safely home',
    ],
  },
  {
    'context': 'Dog walking adventure',
    'events': [
      'Max the beagle pulled on his leash',
      'They discovered a new walking trail',
      'Max sniffed every tree along the path',
      'They surprised a squirrel near the creek',
      'Max splashed in a muddy puddle',
      'A towel was used to clean him off',
      'They stopped for a treat at the pet store',
      'Max fell asleep immediately at home',
    ],
  },
  {
    'context': 'Farmers market visit',
    'events': [
      'Patricia arrived right at opening time',
      'Fresh tomatoes were first on her list',
      'She sampled artisanal cheese at a booth',
      'Organic carrots and lettuce were purchased',
      'A bouquet of fresh flowers caught her eye',
      'Freshly baked bread smelled irresistible',
      'She chatted with the local honey vendor',
      'Patricia carried her filled tote bag home',
    ],
  },
  {
    'context': 'Home renovation project',
    'events': [
      'Tools were gathered in the garage',
      'Old cabinets were removed carefully',
      'New hardware was chosen online',
      'Paint was applied to the cabinet doors',
      'New hinges were installed precisely',
      'The updated kitchen looked modern',
      'Countertops were cleaned thoroughly',
      'Photos were posted on social media',
    ],
  },
  {
    'context': 'Snow day activities',
    'events': [
      'Heavy snow canceled school',
      'Kids pulled on their snowsuits',
      'A snowman was built in the front yard',
      'A snowball fight lasted an hour',
      'Hot chocolate warmed them inside',
      'Wet clothes were hung to dry',
      'Board games were played by the fire',
      'They watched movies under blankets',
    ],
  },
  {
    'context': 'Fishing trip',
    'events': [
      'Dad and son left before sunrise',
      'The boat was launched at the ramp',
      'Bait was threaded onto the hooks',
      'Lines were cast into the deep water',
      'They waited patiently for bites',
      'A large bass was caught at noon',
      'A photo was taken with the fish',
      'They returned to shore by sunset',
    ],
  },
  {
    'context': 'Picnic in the park',
    'events': [
      'A basket was packed with sandwiches',
      'A red checkered blanket was brought',
      'They found a spot under a shady tree',
      'Sandwiches and fruit were enjoyed',
      'Lemonade was poured into cups',
      'Frisbee was played on the grass',
      'They napped in the afternoon sun',
      'Everything was packed up neatly after',
    ],
  },
  {
    'context': 'Crafting workshop',
    'events': [
      'Twelve participants arrived promptly',
      'Supplies were distributed to each table',
      'The instructor demonstrated the technique',
      'Everyone chose their fabric colors',
      'Sewing machines buzzed steadily',
      'Projects took shape over three hours',
      'Final touches were added carefully',
      'Completed items were photographed together',
    ],
  },
  {
    'context': 'Yoga class morning',
    'events': [
      'Mats were unrolled in the studio',
      'Soft music played in the background',
      'The instructor led breathing exercises',
      'Sun salutations began the flow',
      'Warrior poses strengthened their legs',
      'A long shavasana ended the session',
      'Herbal tea was served in the lobby',
      'Everyone left feeling refreshed',
    ],
  },
  {
    'context': 'Book club meeting',
    'events': [
      'Members gathered in the living room',
      'Wine and cheese were served first',
      'Discussion questions were passed out',
      'The main character was debated intensely',
      'Refreshments were refilled mid-meeting',
      'Everyone rated the book numerically',
      'Next month\'s selection was announced',
      'They scheduled the following meeting',
    ],
  },
  {
    'context': 'Photography session',
    'events': [
      'The photographer arrived at golden hour',
      'Camera settings were adjusted for light',
      'The model posed by the old oak tree',
      'Various angles were captured quickly',
      'The light changed and they moved',
      'Close-ups were taken by the stream',
      'Equipment was packed as the sun set',
      'Images were reviewed on the laptop later',
    ],
  },
  {
    'context': 'Volunteer day',
    'events': [
      'Volunteers signed in at the shelter',
      'They were assigned to kitchen duty',
      'Vegetables were chopped for soup',
      'Sandwiches were assembled rapidly',
      'Meals were served promptly at noon',
      'Tables were cleaned after serving',
      'Everyone shared stories about their day',
      'Volunteers clocked out by 3 PM',
    ],
  },
  {
    'context': 'Doctor\'s appointment',
    'events': [
      'Lena arrived fifteen minutes early',
      'She checked in at the reception desk',
      'Vital signs were taken by the nurse',
      'The doctor asked about symptoms',
      'A brief examination was conducted',
      'A prescription was written for medicine',
      'Lena scheduled a follow-up visit',
      'She picked up the medication at the pharmacy',
    ],
  },
  {
    'context': 'Pizza night preparation',
    'events': [
      'Dough was made from scratch at 4 PM',
      'It rose for two hours on the counter',
      'Toppings were prepped and organized',
      'The oven was preheated to 500°F',
      'Pizza was assembled on a peel',
      'It cooked for twelve minutes',
      'Everyone sliced their own pieces',
      'Homemade pizza was declared a success',
    ],
  },
  {
    'context': 'Furniture shopping',
    'events': [
      'They measured their living room first',
      'The showroom had many options',
      'A sectional sofa was particularly comfortable',
      'Fabric samples were compared carefully',
      'The purchase was financed with a plan',
      'Delivery was scheduled for next week',
      'Old furniture was listed for sale online',
      'They celebrated with dinner out',
    ],
  },
  {
    'context': 'Boat ride on the lake',
    'events': [
      'Life jackets were distributed to all',
      'The boat was pushed from the dock',
      'They cruised to the lake\'s center',
      'Swimming was enjoyed for an hour',
      'Sandwiches were eaten on board',
      'Fishing lines were cast from the side',
      'The sunset painted the water orange',
      'They docked safely as dusk fell',
    ],
  },
  {
    'context': 'Science fair project',
    'events': [
      'A hypothesis was written carefully',
      'Materials were gathered from the garage',
      'The experiment was conducted three times',
      'Results were recorded in a notebook',
      'A display board was assembled',
      'Photos were glued to the poster',
      'The project was presented to judges',
      'A blue ribbon was awarded proudly',
    ],
  },
  {
    'context': 'Marathon training run',
    'events': [
      'Running shoes were laced tightly',
      'A hydration pack was filled with water',
      'GPS watch was synced and ready',
      'The first five miles felt effortless',
      'Energy gels were consumed at mile ten',
      'The final three miles were challenging',
      'The twenty-mile run was completed',
      'A long stretch and shower followed',
    ],
  },
  {
    'context': 'Thrift store shopping',
    'events': [
      'Doors opened at 9 AM sharp',
      'Racks were browsed systematically',
      'A vintage leather jacket was discovered',
      'Two books were added to the cart',
      'A quirky lamp was tested and worked',
      'The total came to under twenty dollars',
      'Items were washed at home',
      'Everything fit perfectly in the apartment',
    ],
  },
  {
    'context': 'Pottery class',
    'events': [
      'Clay was centered on the wheel',
      'Hands were wetted to shape the bowl',
      'The wheel spun at medium speed',
      'The form was trimmed with tools',
      'The piece was set aside to dry',
      'Glaze was applied after a week',
      'It was fired in the kiln overnight',
      'The finished bowl was revealed',
    ],
  },
  {
    'context': 'Sunset watching',
    'events': [
      'They drove to the overlook point',
      'A blanket was spread on the grass',
      'The sun began its slow descent',
      'Colors changed from orange to purple',
      'Photos were taken with a phone',
      'A bird soared across the colorful sky',
      'The last sliver disappeared below the horizon',
      'Stars appeared as they drove away',
    ],
  },
  {
    'context': 'Garage sale day',
    'events': [
      'Items were priced with stickers last night',
      'Tables were set up in the driveway',
      'The first customer arrived at 7 AM',
      'Many sales were made before noon',
      'Lunch was a quick sandwich',
      'Afternoon browsers bought little',
      'Remaining items were donated',
      'The garage was cleaned and organized',
    ],
  },
  {
    'context': 'Ice skating rink',
    'events': [
      'Skates were rented at the counter',
      'Laces were tightened securely',
      'The first lap was wobbly and uncertain',
      'Balance improved with each circuit',
      'A hot cocoa break was needed',
      'They attempted a simple spin',
      'The session ended after two hours',
      'Frozen pizza was baked for dinner',
    ],
  },
  {
    'context': 'Thanksgiving dinner prep',
    'events': [
      'The turkey was thawed three days prior',
      'It was stuffed and seasoned early morning',
      'The bird went into the oven at 10 AM',
      'Potatoes were peeled and boiled',
      'Casseroles were assembled side-by-side',
      'Family arrived with pies and wine',
      'All dishes were placed on the table',
      'Everyone shared what they were grateful for',
    ],
  },
  {
    'context': 'Spring cleaning',
    'events': [
      'Windows were opened for fresh air',
      'Closets were emptied completely',
      'Clothes were sorted into three piles',
      'Keepsakes were organized in boxes',
      'Surfaces were dusted and polished',
      'Floors were vacuumed and mopped',
      'Bedding was washed in hot water',
      'The house felt fresh and renewed',
    ],
  },
  {
    'context': 'Breakfast in bed surprise',
    'events': [
      'Lucy woke up early on Sunday',
      'Pancakes were mixed from scratch',
      'Bacon sizzled in the frying pan',
      'A tray was decorated with a flower',
      'Orange juice was poured into a glass',
      'Her partner woke to the surprise',
      'They ate together under the covers',
      'Dishes were cleared afterward',
    ],
  },
  {
    'context': 'First day of school',
    'events': [
      'The alarm rang earlier than usual',
      'A new backpack was loaded carefully',
      'First-day photos were taken outside',
      'The bus arrived promptly at 7:30',
      'Classroom desks were assigned',
      'Textbooks were distributed to students',
      'Lunch was eaten in the cafeteria',
      'Homework was assigned already',
    ],
  },
  {
    'context': 'Spa day',
    'events': [
      'Appointments were booked in advance',
      'Robe and slippers were provided',
      'A massage relaxed tight muscles',
      'A facial rejuvenated the skin',
      'Lunch was served in the lounge',
      'A manicure and pedicure followed',
      'Herbal tea was sipped in the sauna',
      'Emerging feeling completely refreshed',
    ],
  },
  {
    'context': 'Fruit picking',
    'events': [
      'The orchard opened at 8 AM',
      'Baskets were provided at the entrance',
      'Apple trees were heavy with fruit',
      'The best ones were picked from high branches',
      'A ladder was used for the topmost apples',
      'The basket filled quickly in an hour',
      'Apple cider donuts were purchased after',
      'Fresh apple pie was baked that evening',
    ],
  },
  {
    'context': 'Board game night',
    'events': [
      'Friends arrived with snacks',
      'Games were chosen democratically',
      'Tabletop was cleared for the board',
      'Rules were explained to newcomers',
      'The first game lasted two hours',
      'A second, quicker game was chosen',
      'Snacks were refilled midway through',
      'Everyone agreed to meet again next month',
    ],
  },
  {
    'context': 'Learning to ride a bike',
    'events': [
      'Training wheels were removed yesterday',
      'Helmet was adjusted to fit properly',
      'Dad held the seat, running alongside',
      'Pedals were pushed tentatively',
      'Balance was found after several tries',
      'Dad let go without her noticing',
      'She rode independently across the park',
      'Everyone celebrated the achievement',
    ],
  },
  {
    'context': 'Airport security check',
    'events': [
      'Boarding pass and ID were presented',
      'Shoes were removed and placed in bins',
      'Laptop was taken out of the bag',
      'The metal detector beeped once',
      'A quick pat-down was performed',
      'Bags passed through X-ray smoothly',
      'Shoes were put back on quickly',
      'The gate was just a short walk away',
    ],
  },
  {
    'context': 'Building a bookshelf',
    'events': [
      'All pieces were laid out on the floor',
      'Instructions were read thoroughly',
      'Screws were organized by size',
      'The frame was assembled first',
      'Shelves were inserted carefully',
      'The unit was anchored to the wall',
      'Books were arranged alphabetically',
      'The room looked more organized',
    ],
  },
  {
    'context': 'Babysitting evening',
    'events': [
      'Parents left with instructions at 6 PM',
      'Kids were fed macaroni and cheese',
      'A Disney movie was chosen for viewing',
      'Popcorn was popped as a treat',
      'Pajamas were put on after the film',
      'Teeth were brushed with supervision',
      'Bedtime stories were read twice',
      'Kids fell asleep by 9 PM',
    ],
  },
  {
    'context': 'Tire change emergency',
    'events': [
      'The flat tire was noticed on the highway',
      'Hazard lights were turned on immediately',
      'The car was pulled to the shoulder',
      'The spare tire was retrieved from the trunk',
      'Lug nuts were loosened with effort',
      'The jack lifted the car carefully',
      'The spare was installed and tightened',
      'A repair shop was found in the next town',
    ],
  },
  {
    'context': 'Farmers market grand opening',
    'events': [
      'A new market opened downtown',
      'Local vendors set up colorful tents',
      'A band played folk music on stage',
      'Free samples were offered generously',
      'The mayor gave a short speech',
      'Shoppers browsed handmade goods',
      'Fresh produce flew off the tables',
      'The event was deemed a great success',
    ],
  },
  {
    'context': 'Power outage evening',
    'events': [
      'Lights flickered and went dark',
      'Candles were located in the drawer',
      'Flashlights were distributed to kids',
      'Board games were played by candlelight',
      'Non-perishable snacks were eaten',
      'Phones were charged with a power bank',
      'Everyone went to bed early',
      'Power returned mysteriously at 3 AM',
    ],
  },
  {
    'context': 'Job interview preparation',
    'events': [
      'The company was researched thoroughly',
      'Questions were practiced aloud',
      'Professional attire was ironed',
      'Resume copies were printed on quality paper',
      'Directions to the office were mapped',
      'A confident arrival was made early',
      'The interview lasted forty-five minutes',
      'A thank-you email was sent that evening',
    ],
  },
  {
    'context': 'Planting a tree',
    'events': [
      'A suitable spot was chosen in the yard',
      'A hole was dug twice the root ball\'s width',
      'The sapling was positioned carefully',
      'Soil was backfilled and tamped down',
      'Water was applied generously',
      'Mulch was spread around the base',
      'A protective stake was added',
      'Growth will be monitored each spring',
    ],
  },
  {
    'context': 'Tailgate party',
    'events': [
      'The truck arrived in the parking lot at 8 AM',
      'Grills were fired up immediately',
      'Burgers and hot dogs were cooked',
      'Games of cornhole were played',
      'Music blasted from portable speakers',
      'Friends from nearby cars joined in',
      'Everyone headed to the stadium',
      'The home team won the game',
    ],
  },
  {
    'context': 'Learning a new recipe',
    'events': [
      'The recipe was printed from a blog',
      'Ingredients were purchased specially',
      'Steps were read twice for clarity',
      'Onions were diced with a sharp knife',
      'Spices were measured into small bowls',
      'The dish simmered for thirty minutes',
      'Taste testing added more salt',
      'The final result impressed everyone',
    ],
  },
  {
    'context': 'Hardware store run',
    'events': [
      'A broken fixture needed replacement',
      'A diagram was drawn for reference',
      'The store layout was consulted',
      'Staff helped locate the correct aisle',
      'Price comparisons were made',
      'Hardware and tools were purchased',
      'The old fixture was removed at home',
      'The new one installed without issues',
    ],
  },
  {
    'context': 'Morning meditation',
    'events': [
      'The cushion was placed by the window',
      'A timer was set for twenty minutes',
      'Eyes were closed and breathing slowed',
      'Thoughts were acknowledged and released',
      'A bell chimed to signal the end',
      'The room felt peaceful and still',
      'The day began with clarity',
      'A journal entry captured insights',
    ],
  },
  {
    'context': 'Neighborhood block party',
    'events': [
      'Streets were closed to traffic',
      'Tables were set up end-to-end',
      'Potluck dishes arrived throughout the day',
      'Kids decorated bikes for a parade',
      'A DJ played classic hits',
      'Adults competed in a water balloon toss',
      'A talent show featured local kids',
      'The community cleaned up together',
    ],
  },
  {
    'context': 'Unboxing a new gadget',
    'events': [
      'The package arrived a day early',
      'Box was opened with excited impatience',
      'Instructions were read carefully',
      'Charging cable was connected first',
      'Setup wizard guided the process',
      'Settings were customized thoroughly',
      'The first test run was successful',
      'Old device was factory reset',
    ],
  },
  {
    'context': 'Costume party planning',
    'events': [
      'A theme was chosen months ahead',
      'Fabric was purchased at a discount',
      'Pieces were sewn together nightly',
      'Accessories were found at a thrift store',
      'Makeup was tested the week before',
      'Final fittings were made on Friday',
      'The costume was a hit at the party',
      'Awards were given for best dressed',
    ],
  },
];
